name: Deploy slmm
on:
  push:
    branches: [main, stable, prod]

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
          - stage
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup SSH key with passphrase
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519#          eval "$(ssh-agent -s)"
          # Use ssh-add with passphrase via here-string input:
          printf '%s\n' "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      - name: Change Owner e email
        run: |
          git config --global user.email "sergio.marques@puc-campinas.edu.br"
          git config --global user.name "SLMM"  
      - name: Change origin to SSH
        run: |
          git remote set-url origin ssh://sergi3607@sergi3607.c35.integrator.host/home/sergi3607/applications/repositories/api102/.git
          git push origin main
          printf '%s\n' "$SSH_PASSPHRASE"
        
       