name: Deploy slmm
on:
  push:
    branches: [main, stable, prod]

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
          - stage
jobs:
  
       
  Deploy_sl2:    
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H sergi3607.c35.integrator.host >> ~/.ssh/known_hosts

          
 # ssh -v sergi3607@sergi3607.c35.integrator.host || true
         
      - name: Debug SSH
        run: |
          ls -la ~/.ssh
          git --version
          git config --global user.email "sergio.marques@puc-campinas.edu.br"
          git config --global user.name "SLMM"
          git remote set-url origin ssh://sergi3607@sergi3607.c35.integrator.host/home/sergi3607/applications/repositories/api102/.git
          git push -u origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}