name: Deploy slmm 2
on:
  push:
    branches: [stable, prod]

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
          - stage
jobs:
  git-push-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH e executar push com debug
        run: |
          echo "🔐 Configurando chave SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          eval "$(ssh-agent -s)"
          printf '%s\n' "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

          ssh-keyscan -H sergi3607.c35.integrator.host >> ~/.ssh/known_hosts

          echo "⚙️ Configurando Git"
          git config --global user.email "sergio.marques@puc-campinas.edu.br"
          git config --global user.name "SLMM"

          git remote set-url origin ssh://sergi3607@sergi3607.c35.integrator.host/home/sergi3607/applications/repositories/api102/.git || echo "origin já existe"

          echo "🚀 PUSH com debug SSH"
          git push -u origin main
         # GIT_SSH_COMMAND="ssh -vvv" git push -u origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
